/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS Installer API
 * API for installing and updating CasaOS on a device
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

