openapi: 3.0.3

info:
  title: IceWhale Files Backup API
  version: v0.0.1
  description: |
    This is the API for IceWhale Files Backup.

servers:
  - url: /v2/files
security:
  - access_token: []

paths:
  /client/{client_id}/heartbeat:
    get:
      summary: Get heartbeat
      operationId: getHeartbeat
      parameters:
        - $ref: "#/components/parameters/ClientIDParam"
      responses:
        "200":
          $ref: "#/components/responses/HeartbeatOK"
        "404":
          $ref: "#/components/responses/ResponseNotFound"

    post:
      summary: Send heartbeat
      operationId: sendHeartbeat
      parameters:
        - $ref: "#/components/parameters/ClientIDParam"
      responses:
        "200":
          $ref: "#/components/responses/ResponseOK"

  /backup:
    get:
      summary: Get all folder backups
      operationId: getAllFolderBackups
      responses:
        "200":
          $ref: "#/components/responses/AllFolderBackupsOK"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"

  /backup/{client_id}:
    get:
      summary: Get folder backups by client ID
      operationId: getFolderBackupsByClientID
      parameters:
        - $ref: "#/components/parameters/ClientIDParam"
        - $ref: "#/components/parameters/ClientFolderPathParam"
      responses:
        "200":
          $ref: "#/components/responses/FolderBackupsOK"
        "404":
          $ref: "#/components/responses/ResponseNotFound"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"

    post:
      summary: Run a folder backup
      operationId: runFolderBackup
      parameters:
        - $ref: "#/components/parameters/ClientIDParam"
        - $ref: "#/components/parameters/PrepareOnlyParam"
      requestBody:
        $ref: "#/components/requestBodies/FolderBackupRequest"
      responses:
        "200":
          $ref: "#/components/responses/FolderBackupOK"
        "400":
          $ref: "#/components/responses/ResponseBadRequest"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"

    put:
      summary: Complete a folder backup
      operationId: completeFolderBackup
      parameters:
        - $ref: "#/components/parameters/ClientIDParam"
        - $ref: "#/components/parameters/ClientFolderPathParam"
        - $ref: "#/components/parameters/SuccessParam"
      responses:
        "200":
          $ref: "#/components/responses/FolderBackupOK"
        "404":
          $ref: "#/components/responses/ResponseNotFound"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"

    delete:
      summary: Delete a folder backup
      operationId: deleteFolderBackup
      parameters:
        - $ref: "#/components/parameters/ClientIDParam"
        - $ref: "#/components/parameters/ClientFolderPathParam"
      responses:
        "200":
          $ref: "#/components/responses/ResponseOK"
        "404":
          $ref: "#/components/responses/ResponseNotFound"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"

  /devices:
    get:
      summary: Get all devices
      operationId: getAllDevices
      responses:
        "200":
          $ref: "#/components/responses/DevicesOK"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"

  /device/backup:
    post:
      summary: Run a device backup
      operationId: runDeviceBackup
      requestBody:
        $ref: "#/components/requestBodies/DeviceBackupRequest"
      responses:
        "200":
          $ref: "#/components/responses/ResponseOK"
        "400":
          $ref: "#/components/responses/ResponseBadRequest"
        "500":
          $ref: "#/components/responses/ResponseInternalServerError"

components:
  securitySchemes:
    access_token:
      type: apiKey
      in: header
      name: Authorization

  parameters:
    ClientIDParam:
      name: client_id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/ClientID"
      x-go-name: ClientIDParam

    ClientFolderPathParam:
      name: client_folder_path
      in: query
      description: path of the folder from client side to be backed up
      schema:
        type: string
        example: C:\Users\icewhale\Downloads

    SuccessParam:
      name: success
      in: query
      description: get only successful backups
      schema:
        type: boolean
        default: false

    PrepareOnlyParam:
      name: prepare_only
      in: query
      description: prepare only
      schema:
        type: boolean
        default: false

  requestBodies:
    FolderBackupRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/FolderBackup"
    DeviceBackupRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DeviceBackup"

  responses:
    ResponseOK:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseResponse"

    ResponseInternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseResponse"
          example:
            message: "Internal Server Error"

    ResponseNotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseResponse"
          example:
            message: "Not Found"

    ResponseBadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BaseResponse"
          example:
            message: "Bad Request"

    HeartbeatOK:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/BaseResponse"
              - properties:
                  data:
                    properties:
                      last_heartbeat:
                        type: string
                        format: date-time
                        example: "2021-01-01T00:00:00Z"

    FolderBackupOK:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/BaseResponse"
              - properties:
                  data:
                    $ref: "#/components/schemas/FolderBackup"

    AllFolderBackupsOK:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/BaseResponse"
              - properties:
                  data:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        $ref: "#/components/schemas/FolderBackup"

    FolderBackupsOK:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/BaseResponse"
              - properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/FolderBackup"

    DevicesOK:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/BaseResponse"
              - properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/DeviceInfo"

  schemas:
    DeviceInfo:
      type: object
      properties:
        id:
          type: string
          description: Device ID(serial number)
          example: "SN123456789"
        authorized:
          type: boolean
          description: Indicates if the device is authorized
          example: true
        name:
          type: string
          description: Device name
          example: "My Phone"
        connection:
          type: string
          description: Connection type, can be USB or IP
          example: "USB"
        speed:
          type: integer
          format: int64
          description: Connection speed
          example: 480000000
        product_name:
          type: string
          description: Product name of the device
          example: "iPhone 12"
        brand:
          type: string
          description: Device brand
          example: "Apple"
        os:
          type: string
          description: Operating system of the device, can be ANDROID or IOS
          example: "IOS"
        version:
          type: string
          description: Version of the operating system
          example: "14.4"
        img_url:
          type: string
          description: URL of the device image
          example: "https://example.com/device.jpg"
        total:
          type: integer
          format: int64
          description: Total storage of the device in bytes
          example: 128000000000
        data_available:
          type: integer
          format: int64
          description: Available data storage in bytes
          example: 64000000000
        sys_available:
          type: integer
          format: int64
          description: Available system storage in bytes
          example: 8000000000
        is_charging:
          type: boolean
          description: Whether the device is currently charging
          example: true
        battery_level:
          type: string
          description: Battery level of the device
          example: "80%"
        will_encrypt:
          type: boolean
          description: Indicates if the device will be encrypted
          example: true
        progress:
          type: string
          description: Progress of the ongoing operation
          example: "50%"
        last_time:
          type: string
          description: Timestamp of the last operation
          example: "2023-09-20T12:34:56Z"
        last_error:
          type: string
          description: Last error that occurred
          example: "No space left on device"
      required:
        - id
        - authorized

    BaseResponse:
      properties:
        message:
          description: message returned by server side if there is any
          type: string
          example: ""

    ClientID:
      type: string
      readOnly: true
      example: "client123"
      x-go-name: ClientID

    FolderBackup:
      required:
        - client_id
        - client_folder_path
        - backup_folder_path
      properties:
        client_id:
          $ref: "#/components/schemas/ClientID"

        client_name:
          description: name of the client
          type: string
          example: "John's Computer"

        client_type:
          description: type of the client
          type: string
          example: "Windows"

        client_folder_path:
          description: |
            path of the folder from client side to be backed up

            > This path is case sensitive. Make sure the value is consistent when client runs on Windows.

          type: string
          example: C:\Users\icewhale\Downloads

        client_folder_file_sizes:
          description: |
            sizes of files under the folder from client side to be backed up

            > - This key is case sensitive. Make sure the value is consistent when client runs on Windows.
            > - The size is in bytes.

          writeOnly: true
          type: object
          additionalProperties:
            type: integer
            format: int64
          example:
            'C:\Users\icewhale\Downloads\1.txt': 123
            'C:\Users\icewhale\Downloads\Movies\2.mp4': 4567890

        client_folder_file_hashes:
          description: |
            hashes of files under the folder from client side to be backed up

            > - The hash algorithm is xxHash (https://cyan4973.github.io/xxHash)
            > - This key is case sensitive. Make sure the value is consistent when client runs on Windows.

          writeOnly: true
          type: object
          additionalProperties:
            type: string
          example:
            'C:\Users\icewhale\Downloads\1.txt': "d41d8cd98f00b204e9800998ecf8427e"
            'C:\Users\icewhale\Downloads\Movies\2.mp4': "d41d8cd98f00b204e9800998ecf8427e"

        client_folder_file_transfer_list:
          description: |
            list of files to be transferred from client side to server side

            > This list should be provided by the server side in the response. It is read only to client side.
          readOnly: true
          type: object
          additionalProperties:
            type: string
          example:
            'C:\Users\icewhale\Downloads\1.txt': "Backup/SomeClientID/C/Users/icewhale/Downloads/1.txt"
            'C:\Users\icewhale\Downloads\Movies\2.mp4': "Backup/SomeClientID/C/Users/icewhale/Downloads/Movies/2.mp4"
        keep_history_copy:
          description: |
            whether to keep history copy of files in the folder backup

            > - If set to `true`, will keep history copy of files in the folder backup.
            > - If set to `false`, will only keep the latest version of files in the folder backup.
          type: boolean
          default: true

        backup_folder_path:
          description: |
            full path of the folder from server side to store backup files
          type: string
          example: /DATA/Backup/SomeClientID/C/Users/icewhale/Downloads

        backup_folder_count:
          description: number of files in the folder backup
          readOnly: true
          type: integer
          example: 2

        backup_folder_size:
          description: size of the folder backup in bytes
          readOnly: true
          type: integer
          format: int64
          example: 1024

        last_backup_time:
          description: last backup time in milliseconds
          readOnly: true
          type: integer
          format: int64
          example: 1681159361000

        last_backup_succeeded:
          readOnly: true
          type: boolean

        in_progress:
          readOnly: true
          type: boolean

        transfer_type:
          readOnly: true
          type: string
          example: webdav

        transfer_port:
          readOnly: true
          type: string
          example: "45212"

    DeviceBackup:
      required:
        - id
        - os
      properties:
        id:
          type: string
          example: "00008030-00140C56143040xx"
        os:
          type: string
          example: "IOS"
        con:
          type: string
          example: "USB"
