name: Release NPM Package

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/setup-node@v3
          with:
            node-version: 16
            registry-url: https://registry.npmjs.org/

        - name: Generate SDK
          run: |
            npm cache clean --force
            npm install @openapitools/openapi-generator-cli -g
        
        - name: Build Installer SDK
          run: |
            openapi-generator-cli generate -g typescript-axios -i ./casaos-installer/installer/openapi.yaml -o ./zimaos-openapi/installer
            openapi-generator-cli generate -g typescript-axios -i ./zimaos-local-storage/local_storage/openapi.yaml -o ./zimaos-openapi/localstorage/v2
            openapi-generator-cli generate -g typescript-axios -i ./zimaos-local-storage/local_storage/openapi_v1.yaml -o ./zimaos-openapi/localstorage/v1

