name: Validate OpenAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install OpenAPI CLI
        run: npm install -g @redocly/openapi-cli

      - name: Validate OpenAPI files
        run: |
          for file in $(find . -name '*.yaml' -o -name '*.yml' -o -name '*.json'); do
            echo "Validating $file"
            openapi lint $file
          done
